In [1]:
import numpy as np
import pandas as pd

import wmfdata as wmf
from wmfdata.utils import get_dblist

# Parameters

In [2]:
# Data will be generated for the 12 months ending with and including SNAPSHOT
# This is also the mediawiki_history snapshot necessary for the calculations.
SNAPSHOT = "2024-01"

# An ordered list of wikis for which to output each metric after it is generated. 
# This is useful for spot checking the values generated against the previous snapshot.
WIKIS_TO_CHECK = [
    "enwiki",
    "eswiki",
    "jawiki",
    "dewiki",
    "frwiki",
    "ruwiki"
]

In [3]:
snapshot = pd.Period(SNAPSHOT)
start = (snapshot - 11).start_time
end = (snapshot + 1).start_time
# Used to name the output files
file_stem = snapshot.strftime("%b_%Y")

# Start included, end excluded
query_vars = dict(
    snapshot=snapshot.strftime("%Y-%m"),
    start=start.strftime('%Y-%m-%d'), 
    end=end.strftime('%Y-%m-%d'),
    ym_start=start.strftime("%Y-%m"),
    ym_end=end.strftime("%Y-%m"),
    pv_start=start.strftime("%Y%m"),
    pv_end=end.strftime("%Y%m"),
    # New editor retention needs different time boundaries, since we define retention
    # in a given month as the status of the new users who registered two months prior
    ner_cohort_start=(snapshot - 14).strftime("%Y-%m"),
    ner_cohort_end=(snapshot - 1).strftime("%Y-%m")
)

# Spark setup

In [4]:
wmf.spark.create_session(type="yarn-large")

SPARK_HOME: /usr/lib/spark3
Using Hadoop client lib jars at 3.2.0, provided by Spark.
PYSPARK_PYTHON=/opt/conda-analytics/bin/python3

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/03/04 23:44:36 WARN SparkConf: Note that spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone/kubernetes and LOCAL_DIRS in YARN).
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12000. Attempting port 12001.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12001. Attempting port 12002.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12002. Attempting port 12003.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12003. Attempting port 12004.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12004. Attempting port 12005.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12005. Attempting port 12006.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12006. Attempting port 12007.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12007. Attempting port 12008.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12008. Attempting port 12009.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12009. Attempting port 12010.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12010. Attempting port 12011.
24/03/04 23:44:37 WARN Utils: Service 'sparkDriver' could not bind on port 12011. Attempting port 12012.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
24/03/04 23:44:37 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13000. Attempting port 13001.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13001. Attempting port 13002.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13002. Attempting port 13003.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13003. Attempting port 13004.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13004. Attempting port 13005.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13005. Attempting port 13006.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13006. Attempting port 13007.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13007. Attempting port 13008.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13008. Attempting port 13009.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13009. Attempting port 13010.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13010. Attempting port 13011.
24/03/04 23:44:45 WARN Utils: Service 'org.apache.spark.network.netty.NettyBlockTransferService' could not bind on port 13011. Attempting port 13012.
24/03/04 23:44:46 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!

# List of wikis

In [5]:
# The canonical_data.wikis table is not automatically updated,
# so you should first update it manually by running the notebook:
# https://github.com/wikimedia-research/canonical-data/blob/master/generation/wikis.ipynb
#
# This is important since new wikis are regularly opened and old ones are sometimes closed.
wikis = wmf.spark.run("""
SELECT
  database_code,
  database_group AS project_code,
  language_code,
  domain_name,
  language_name,
  english_name as wiki_name
FROM canonical_data.wikis
WHERE
  database_group IN (
    "commons", "incubator", "foundation", "mediawiki", "meta", "sources",
    "species","wikibooks", "wikidata", "wikinews", "wikipedia", "wikiquote",
    "wikisource", "wikiversity", "wikivoyage", "wiktionary"
  )
  AND status = "open"
  AND visibility = "public"
  AND editability = "public"
""")

# Check for missing wikis in mediawiki_history

Sometimes, wikis are not added to mediawiki_history after they're created (e.g. [T299548](https://phabricator.wikimedia.org/T299548), [T220456](https://phabricator.wikimedia.org/T220456)). Let's check for that.

In [6]:
mwh_wikis = wmf.spark.run("""
SELECT DISTINCT wiki_db AS database_code
FROM wmf.mediawiki_history
""".format(**query_vars))

24/03/04 23:45:02 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
24/03/04 23:45:24 WARN SharedInMemoryCache: Evicting cached table partition metadata from memory due to size constraints (spark.sql.hive.filesourcePartitionFileCacheSize = 262144000 bytes). This may impact query planning performance.

In [7]:
mwh_missing_wikis = set(wikis["database_code"]) - set(mwh_wikis["database_code"])
mwh_missing_wikis

set()

If there are missing wikis, they should be reported to Data Engineering. In the meantime, let's continue generating the data for the remaining wikis.

In [8]:
wikis = wikis.drop(
    index=wikis.query("database_code in @mwh_missing_wikis").index
)

# Data collection

In [9]:
def merge_in(df, on="database_code"):
    global wikis
    wikis = pd.merge(wikis, df, how="left", on=on).fillna(0)

wikis_to_check = (
    pd.DataFrame({"database_code": WIKIS_TO_CHECK})
    .merge(wikis, how="left", on="database_code")
)

def check(df, index_col="database_code"):
    indexes = wikis_to_check[index_col].to_frame()
    return indexes.merge(df, how="left", on=index_col)

## Unique devices

In [10]:
ud = wmf.spark.run("""
SELECT
    -- Strip mobile subdomains so mobile and desktop sites are combined.
    -- This needs to be replaced with a join on canonical data. For details, see
    -- https://datahub.wikimedia.org/glossaryTerm/urn:li:glossaryTerm:d946d194-afe1-485b-8b4f-1df675e9f68d/
    REGEXP_REPLACE(
        REGEXP_REPLACE(
            -- The canonical domains for Wikidata and MediaWiki.org start with `www`, which 
            -- gets _replaced_ by the mobile subdomain. Combine the two possibilites for each site.
            REGEXP_REPLACE(
                REGEXP_REPLACE(domain, "^m\\\\.wikidata", "www.wikidata"),
            "^m\\\\.mediawiki", "www.mediawiki"),
        "^m\\\\.", ""),
    "\\\\.m\\\\.", ".") AS domain_name,
    SUM(uniques_estimate) / 12 AS monthly_unique_devices,
    SUM(IF(
        (domain REGEXP "^m\\\\." OR  domain REGEXP "\\\\.m\\\\."),
        uniques_estimate,
        0
    )) / SUM(uniques_estimate) AS mobile_unique_devices
FROM wmf_readership.unique_devices_per_domain_monthly
WHERE 
    day >= "{start}" 
    AND day < "{end}"  
GROUP BY    
    REGEXP_REPLACE(
        REGEXP_REPLACE(
            -- The canonical domains for Wikidata and MediaWiki.org start with `www`, which 
            -- gets _replaced_ by the mobile subdomain. Combine the two possibilites for each site.
            REGEXP_REPLACE(
                REGEXP_REPLACE(domain, "^m\\\\.wikidata", "www.wikidata"),
            "^m\\\\.mediawiki", "www.mediawiki"),
        "^m\\\\.", ""),
    "\\\\.m\\\\.", ".")
""".format(**query_vars))

In [11]:
check(ud, index_col="domain_name")

        domain_name  monthly_unique_devices  mobile_unique_devices
0  en.wikipedia.org            8.886000e+08               0.737466
1  es.wikipedia.org            1.381780e+08               0.743219
2  ja.wikipedia.org            1.007369e+08               0.743380
3  de.wikipedia.org            1.003334e+08               0.645767
4  fr.wikipedia.org            9.744296e+07               0.703772
5  ru.wikipedia.org            1.033756e+08               0.728028

In [12]:
merge_in(ud, on="domain_name")

## Pageviews

In [13]:
pv = wmf.spark.run("""
SELECT
    IF(
        project IN ("mediawiki", "wikidata"),
        CONCAT("www.", project, ".org"),
        CONCAT(project, ".org")
    ) AS domain_name, 
    SUM(view_count) / 12 AS monthly_pageviews,
    SUM(CASE WHEN access_method = "mobile web" THEN view_count END)
        / SUM(view_count) AS mobile_web_pageviews,
    SUM(CASE WHEN access_method = "mobile app" THEN view_count END)
        / SUM(view_COUNT) AS mobile_app_pageviews
FROM wmf.projectview_hourly
WHERE
    agent_type = "user" 
    AND CONCAT(year, LPAD(month, 2, "0")) >= "{pv_start}" 
    AND CONCAT(year, LPAD(month, 2, "0")) < "{pv_end}"
GROUP BY
    IF(
        project IN ("mediawiki", "wikidata"),
        CONCAT("www.", project, ".org"),
        CONCAT(project, ".org")
    )
""".format(**query_vars))

In [14]:
check(pv, index_col="domain_name")

,domain_name,monthly_pageviews,mobile_web_pageviews,mobile_app_pageviews
0,en.wikipedia.org,7.689967e+09,0.654493,0.023393
1,es.wikipedia.org,8.788715e+08,0.728027,0.007123
2,ja.wikipedia.org,9.212307e+08,0.659127,0.010585
3,de.wikipedia.org,8.139403e+08,0.573086,0.049401
4,fr.wikipedia.org,7.184588e+08,0.604195,0.016843
5,ru.wikipedia.org,8.996049e+08,0.679241,0.014267

In [15]:
merge_in(pv, on="domain_name")

## Monthly editors

In [16]:
me = wmf.spark.run("""
SELECT
    wiki AS database_code,
    COUNT(*) / 12 AS monthly_editors,
    SUM(CAST(content_edits >= 5 AS INT)) / 12 AS monthly_active_editors,
    SUM(CAST(
        content_edits >= 5
        AND TRUNC(user_registration, 'MM') = TRUNC(month, 'MM') 
    AS INT)) / 12 AS monthly_new_active_editors
FROM wmf_product.editor_month
WHERE
    month >= "{start}" 
    AND month < "{end}" 
    AND user_id != 0
    -- Despite the name, this field identifies bots using both the name and group strategies
    AND NOT bot_by_group
GROUP BY wiki
""".format(**query_vars))

In [17]:
check(me)

,database_code,monthly_editors,monthly_active_editors,monthly_new_active_editors
0,enwiki,126410.083333,31195.500000,4254.916667
1,eswiki,15605.250000,4342.416667,885.750000
2,jawiki,14250.833333,4934.666667,676.083333
3,dewiki,18348.916667,5150.666667,362.916667
4,frwiki,18334.750000,4907.750000,636.250000
5,ruwiki,11067.833333,3208.500000,457.250000

In [18]:
merge_in(me)

## Monthly active administrators

In [19]:
maa = wmf.spark.run("""
SELECT
    wiki AS database_code,
    SUM(monthly_active_administrators) / 12 AS monthly_active_administrators
FROM (
    SELECT
        wiki_db AS wiki,
        SUBSTR(log_timestamp, 1, 6) AS month,
        COUNT(DISTINCT log_actor) AS monthly_active_administrators
    FROM wmf_raw.mediawiki_logging
    WHERE
        log_type IN ("block", "delete", "protect", "rights")
        -- Omit the "delete_redir", "move_prot", and "autopromote" actions, which can be done by regular users
        AND log_action NOT IN ("autopromote", "delete_redir", "move_prot")
        AND log_timestamp >= "{pv_start}" 
        AND log_timestamp < "{pv_end}" 
        AND snapshot = "{snapshot}"
    GROUP BY wiki_db, SUBSTR(log_timestamp, 1, 6)
) mae
GROUP BY wiki
""".format(**query_vars))

24/03/04 23:48:10 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
24/03/04 23:48:31 WARN DAGScheduler: Broadcasting large task binary with size 1105.6 KiB

In [20]:
check(maa)

  database_code  monthly_active_administrators
0        enwiki                     398.000000
1        eswiki                      44.250000
2        jawiki                      29.916667
3        dewiki                     124.916667
4        frwiki                      87.833333
5        ruwiki                      87.000000

In [21]:
merge_in(maa)

## Majority-mobile editors proportion

In [22]:
mmep = wmf.spark.run("""
WITH user AS (
    SELECT 
        wiki_db AS database_code,
        SUM(CAST(ARRAY_CONTAINS(revision_tags, "mobile edit") AS INT))
            / COUNT(*) AS mobile_editing_proportion
    FROM wmf.mediawiki_history
    WHERE
        event_entity = "revision" 
        AND event_type = "create" 
        AND snapshot = "{snapshot}" 
        AND event_timestamp >= "{start}" 
        AND event_timestamp < "{end}"
        AND NOT event_user_is_anonymous
        AND SIZE(event_user_is_bot_by_historical) = 0
    GROUP BY
        wiki_db,
        event_user_text
)
SELECT
   database_code,
   SUM(CAST(mobile_editing_proportion > 0.5 AS INT))
       / COUNT(*) AS majority_mobile_editors
FROM user
GROUP BY database_code
""".format(**query_vars))

In [23]:
check(mmep)

  database_code  majority_mobile_editors
0        enwiki                 0.267968
1        eswiki                 0.329679
2        jawiki                 0.288731
3        dewiki                 0.172797
4        frwiki                 0.208703
5        ruwiki                 0.384692

In [24]:
merge_in(mmep)

## New editor retention

In [25]:
ner = wmf.spark.run(
"""
SELECT
    wiki AS database_code,
    SUM(CAST(2nd_month_edits >= 1 AS INT))
        / SUM(CAST(1st_month_edits >= 1 AS INT)) AS second_month_new_editor_retention
FROM wmf_product.new_editors
WHERE 
    cohort >= "{ner_cohort_start}" and
    cohort < "{ner_cohort_end}"
GROUP BY wiki
""".format(**query_vars))

In [26]:
check(ner, "database_code")

  database_code  second_month_new_editor_retention
0        enwiki                           0.076758
1        eswiki                           0.048676
2        jawiki                           0.097214
3        dewiki                           0.070290
4        frwiki                           0.061452
5        ruwiki                           0.058594

In [27]:
merge_in(ner)

## Monthly non-bot edits

In [28]:
mnbe = wmf.spark.run("""
SELECT
    CONCAT(project, ".org") AS domain_name,
    SUM(edit_count) / 12 AS monthly_nonbot_edits,
    SUM(CASE WHEN ARRAY_CONTAINS(revision_tags, "mobile edit") THEN edit_count END)
        / SUM(edit_count) AS mobile_edits,
    SUM(CASE WHEN ARRAY_CONTAINS(revision_tags, "visualeditor") THEN edit_count END)
        / SUM(edit_count) AS visual_edits,
    SUM(CASE WHEN user_is_anonymous THEN edit_count END) / SUM(edit_count) AS anonymous_edits
FROM wmf.edit_hourly
WHERE
    ts >= "{start}"
    AND ts < "{end}"
    AND NOT user_is_bot
    AND snapshot = "{snapshot}"
GROUP BY CONCAT(project, ".org")
""".format(**query_vars))

In [29]:
check(mnbe, index_col="domain_name")

,domain_name,monthly_nonbot_edits,mobile_edits,visual_edits,anonymous_edits
0,en.wikipedia.org,4.243106e+06,0.160909,0.107227,0.151290
1,es.wikipedia.org,5.860648e+05,0.257324,0.172240,0.250279
2,ja.wikipedia.org,3.795027e+05,0.253854,0.152733,0.207090
3,de.wikipedia.org,7.333952e+05,0.061972,0.113080,0.089409
4,fr.wikipedia.org,7.079225e+05,0.114163,0.184577,0.118540
5,ru.wikipedia.org,4.553445e+05,0.147396,0.156419,0.177114

In [30]:
merge_in(mnbe, on="domain_name")

## Bot editing proportion

In [31]:
bep = wmf.spark.run("""
SELECT
   CONCAT(project, ".org") AS domain_name,
   SUM(CASE WHEN user_is_bot THEN edit_count END)
        / SUM(edit_count) AS bot_edits
FROM wmf.edit_hourly
WHERE
    ts  >= "{start}" 
    AND ts  < "{end}"
    AND snapshot = "{snapshot}"
GROUP BY CONCAT(project, ".org")
""".format(**query_vars))

In [32]:
check(bep, index_col="domain_name")

        domain_name  bot_edits
0  en.wikipedia.org   0.214410
1  es.wikipedia.org   0.211506
2  ja.wikipedia.org   0.158742
3  de.wikipedia.org   0.148590
4  fr.wikipedia.org   0.232547
5  ru.wikipedia.org   0.288456

In [33]:
merge_in(bep, on="domain_name")

## Revert rate

In [34]:
rr = wmf.spark.run("""
    SELECT
        wiki_db AS database_code,
        SUM(CAST(revision_is_identity_reverted AS INT)) / COUNT(*) AS revert_rate
    FROM
        wmf.mediawiki_history
    WHERE
        event_entity = "revision" 
        AND event_type = "create" 
        AND snapshot = "{snapshot}" 
        AND event_timestamp >= "{start}" 
        AND event_timestamp < "{end}" 
        AND SIZE(event_user_is_bot_by_historical) = 0 
    GROUP BY wiki_db
""".format(**query_vars))

In [35]:
check(rr)

  database_code  revert_rate
0        enwiki     0.098533
1        eswiki     0.153527
2        jawiki     0.059258
3        dewiki     0.072109
4        frwiki     0.061272
5        ruwiki     0.107054

In [36]:
merge_in(rr)

## Edits Gini coefficient

In [37]:
user_edits = wmf.spark.run("""
SELECT
    wiki_db AS wiki,
    COUNT(*) AS user_edits
FROM
    wmf.mediawiki_history
WHERE
    event_entity = "revision" 
    AND event_type = "create" 
    AND snapshot = "{snapshot}" 
    AND event_timestamp >= "{start}" 
    AND event_timestamp < "{end}" 
    AND SIZE(event_user_is_bot_by_historical) = 0
GROUP BY
    wiki_db,
    event_user_id
""".format(**query_vars))

In [38]:
# from https://github.com/oliviaguest/gini
# licensed under CC0 (public domain)
def gini(array):
    """Calculate the Gini coefficient of a numpy array."""
    # based on bottom eq:
    # http://www.statsdirect.com/help/generatedimages/equations/equation154.svg
    # FROM:
    # http://www.statsdirect.com/help/default.htm#nonparametric_methods/gini.htm
    # All values are treated equally, arrays must be 1d:
    array = array.flatten()
    if np.amin(array) < 0:
        # Values cannot be negative:
        array -= np.amin(array)
    # Values cannot be 0:
    array = array + 0.0000001
    # Values must be sorted:
    array = np.sort(array)
    # Index per array element:
    index = np.arange(1, array.shape[0] + 1)
    # Number of array elements:
    n = array.shape[0]
    # Gini coefficient:
    return ((np.sum((2 * index - n - 1) * array)) / (n * np.sum(array)))

egc = (
    user_edits
    .groupby("wiki")
    .apply(lambda g: gini(g["user_edits"].values))
    .reset_index()
)

egc.columns = ["database_code", "edits_Gini_coefficient"]

In [39]:
check(egc)

  database_code  edits_Gini_coefficient
0        enwiki                0.954791
1        eswiki                0.959630
2        jawiki                0.935114
3        dewiki                0.960706
4        frwiki                0.960463
5        ruwiki                0.961491

In [40]:
merge_in(egc)

## Content pages

Note that this query gives the number of content pages _at query time_, not at the end of the snapshot period. Unless the gap between those times is many months, the difference should be pretty small.

Ideally, we would query `mediawiki_history` or the AQS API instead for the count as of the end of the snapshot period. However, this would introduce a new problem: the official [content pages definition](https://www.mediawiki.org/wiki/Manual:Article_count) specifies that pages (in addition to being in a content namespace, not being deleted, and not being a redirect) must also contain one internal link. This information isn't available in `mediawiki_history`, and the article count available through the AQS API probably doesn't take it into account either.

In [41]:
wikis_list = wikis["database_code"].tolist()

ac = wmf.mariadb.run("""
SELECT
    DATABASE() AS database_code,
    ss_good_articles AS content_pages
FROM site_stats
""", wikis_list)

# Some wikis have sharded site_stats tables, which means the output will have multiple rows
# for that wiki that need to be summed up.
# Documented on https://www.mediawiki.org/wiki/Manual:Site_stats_table
ac = ac.groupby("database_code").sum().reset_index()

/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/hghani/.conda/envs/2024-03-04T23.26.17_hghani/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [42]:
check(ac)

  database_code  content_pages
0        enwiki        6792544
1        eswiki        1936291
2        jawiki        1406455
3        dewiki        2888302
4        frwiki        2596206
5        ruwiki        1967542

In [43]:
merge_in(ac)

## All-time content edits

In [44]:
atce = wmf.spark.run("""
SELECT
    wiki_db AS database_code,
    COUNT(*) AS all_time_content_edits
FROM
    wmf.mediawiki_history
WHERE
    event_entity = "revision" 
    AND event_type = "create" 
    AND snapshot = "{snapshot}" 
    AND page_namespace_is_content
    AND SIZE(event_user_is_bot_by_historical) = 0 
GROUP BY wiki_db
""".format(**query_vars))

In [45]:
check(atce)

  database_code  all_time_content_edits
0        enwiki               733834743
1        eswiki               107569636
2        jawiki                75862906
3        dewiki               149301345
4        frwiki               124258542
5        ruwiki                81459552

In [46]:
merge_in(atce)

## Script direction

In [47]:
rtl_wikis = get_dblist("rtl")
rtl = pd.DataFrame({"database_code": rtl_wikis, "script_direction": "right-to-left"})
merge_in(rtl)
wikis["script_direction"] = wikis["script_direction"].replace({0: "left-to-right"})

## Unique devices per editor

In [48]:
wikis["unique_devices_per_editor"] = wikis["monthly_unique_devices"] / wikis["monthly_editors"]

In [49]:
wikis = wikis.replace([np.inf], 0)

## Overall size rank

In [50]:
size = np.sqrt(wikis["monthly_unique_devices"] * wikis["monthly_active_editors"])
rank = size.rank(method="min", na_option="bottom", ascending=False)
wikis["overall_size_rank"] = rank

## Edits per content page

In [51]:
wikis["all_time_edits_per_content_page"] = wikis["all_time_content_edits"] / wikis["content_pages"]

# Readying for output

In [52]:
wikis_formatted = (
    wikis[[
        "overall_size_rank",
        "monthly_unique_devices",
        "mobile_unique_devices",
        "monthly_pageviews",
        "mobile_web_pageviews",
        "mobile_app_pageviews",
        "unique_devices_per_editor",
        "monthly_editors",
        "majority_mobile_editors",
        "monthly_active_editors",
        "monthly_active_administrators",
        "monthly_new_active_editors",
        "second_month_new_editor_retention",
        "bot_edits",
        "monthly_nonbot_edits",
        "mobile_edits",
        "visual_edits",
        "anonymous_edits",
        "revert_rate",
        "edits_Gini_coefficient",
        "content_pages",
        "all_time_content_edits",
        "all_time_edits_per_content_page",
        "script_direction",
        "database_code",
        "project_code",
        "language_code",
        "language_name",
        "domain_name",
        "wiki_name"
    ]].astype({
        # These columns are not monthly averages and will never have a fractional component
        "overall_size_rank": int,
        "content_pages": int,
        "all_time_content_edits": int
    })
    .sort_values("overall_size_rank")
)

# Convert underscores to spaces in column names in the final step, to avoid having to
# work with spaces beforehand
wikis_formatted = wikis_formatted.rename(columns=lambda c: c.replace("_", " "))

## Output TSV

In [53]:
wikis_formatted.to_csv(
    f"snapshots/{file_stem}.tsv",
    sep="\t",
    float_format="%0.4f",
    index=False
)